export const QUOTES: { text: string; author: string }[] = [
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Real estate cannot be lost or stolen, nor can it be carried away. It is about as safe an investment as exists.", author: "Franklin D. Roosevelt" },
  { text: "Ninety percent of all millionaires become so through owning real estate.", author: "Andrew Carnegie" },
  { text: "Buy land, they're not making it anymore.", author: "Mark Twain" },
  { text: "Don't wait to buy real estate. Buy real estate and wait.", author: "Will Rogers" },
  { text: "The best investment on earth is earth.", author: "Louis Glickman" },
  { text: "Marketing is no longer about the stuff you make, but about the stories you tell.", author: "Seth Godin" },
  { text: "Content builds relationships. Relationships are built on trust. Trust drives revenue.", author: "Andrew Davis" },
  { text: "People don't buy what you do, they buy why you do it.", author: "Simon Sinek" },
  { text: "Make a customer, not a sale.", author: "Katherine Barchetti" },
  { text: "The best marketing doesn't feel like marketing.", author: "Tom Fishburne" },
  { text: "Talent wins games, but teamwork wins championships.", author: "Michael Jordan" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "Coming together is a beginning, staying together is progress, working together is success.", author: "Henry Ford" },
  { text: "None of us is as smart as all of us.", author: "Ken Blanchard" },
  { text: "Great things in business are never done by one person; they're done by a team of people.", author: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "What gets measured gets managed.", author: "Peter Drucker" },
  { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { text: "Your network is your net worth.", author: "Porter Gale" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John Maxwell" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "If you are not taking care of your customer, your competitor will.", author: "Bob Hooey" },
  { text: "Selling is really about having conversations with people.", author: "Lori Richardson" },
  { text: "Every sale has five obstacles: no need, no money, no hurry, no desire, no trust.", author: "Zig Ziglar" },
  { text: "Timid salesmen have skinny kids.", author: "Zig Ziglar" },
  { text: "Stop selling. Start helping.", author: "Zig Ziglar" },
  { text: "The home is the chief school of human virtues.", author: "William Ellery Channing" },
  { text: "There is no place like home.", author: "L. Frank Baum" },
  { text: "A house is made of walls and beams; a home is built with love and dreams.", author: "Ralph Waldo Emerson" },
  { text: "He is happiest, be he king or peasant, who finds peace in his home.", author: "Johann Wolfgang von Goethe" },
  { text: "Buy on the fringe and wait. Put your land near a growing city.", author: "Jesse L. Livermore" },
  { text: "Landlords grow rich in their sleep.", author: "John Stuart Mill" },
  { text: "To be successful in real estate, you must always and consistently put your clients' best interests first.", author: "Anthony Hitt" },
  { text: "In real estate, you make 10 percent of your money because you're a genius and 90 percent because you catch a great wave.", author: "Jeff Greene" },
  { text: "Find out where the people are going and buy the land before they get there.", author: "William Penn Adair" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Ideas are easy. Implementation is hard.", author: "Guy Kawasaki" },
  { text: "If you double the number of experiments you do per year, you're going to double your inventiveness.", author: "Jeff Bezos" },
  { text: "Good marketing makes the company look smart. Great marketing makes the customer feel smart.", author: "Joe Chernov" },
  { text: "Build something 100 people love, not something 1 million people kind of like.", author: "Brian Chesky" },
  { text: "The aim of marketing is to know the customer so well the product sells itself.", author: "Peter Drucker" },
  { text: "Either write something worth reading or do something worth writing about.", author: "Benjamin Franklin" },
  { text: "Don't find customers for your products, find products for your customers.", author: "Seth Godin" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Success usually comes to those too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "You miss 100 percent of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Great marketing is about telling your story in such a way that it compels people to buy.", author: "Unknown" },
  { text: "The customer's perception is your reality.", author: "Kate Zabriskie" },
  { text: "Branding is what people say about you when you're not in the room.", author: "Jeff Bezos" },
  { text: "A brand is no longer what we tell the consumer it is, it is what consumers tell each other it is.", author: "Scott Cook" },
  { text: "Marketing without data is like driving with your eyes closed.", author: "Dan Zarrella" },
  { text: "Teamwork makes the dream work, but a vision becomes a nightmare when the leader has a dream and the team doesn't have a ladder.", author: "John Maxwell" },
  { text: "If everyone is moving forward together, then success takes care of itself.", author: "Henry Ford" },
  { text: "Surround yourself with people who push you to do better.", author: "Unknown" },
  { text: "Individually we are one drop. Together we are an ocean.", author: "Ryunosuke Satoro" },
  { text: "The strength of the team is each individual member. The strength of each member is the team.", author: "Phil Jackson" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Dream big, start small, but most of all, start.", author: "Simon Sinek" },
  { text: "Working hard for something we don't care about is called stress; working hard for something we love is called passion.", author: "Simon Sinek" },
  { text: "The grass is greener where you water it.", author: "Neil Barringham" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Coffee first. Schemes later.", author: "Unknown" },
  { text: "I'm not bossy, I just have better ideas.", author: "Unknown" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "First, they ignore you. Then they copy you.", author: "Unknown" },
];

function dayOfYear(d: Date): number {
  const start = Date.UTC(d.getUTCFullYear(), 0, 0);
  const now = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
  return Math.floor((now - start) / 86400000);
}

export function getQuoteOfTheDay(date: Date = new Date()) {
  const idx = dayOfYear(date) % QUOTES.length;
  return QUOTES[idx];
}
