export default {
  externals: {
    external: [
      "@tanstack/react-router",
      "@tanstack/react-query",
      "sonner",
      "@radix-ui/react-label",
      "@radix-ui/react-select",
      "@radix-ui/react-radio-group",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-dialog",
      "@radix-ui/react-popover",
      "@radix-ui/react-tabs",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-progress",
      "@radix-ui/react-switch",
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-collection",
      "@radix-ui/react-dismissable-layer",
      "@radix-ui/react-focus-guards",
      "@radix-ui/react-focus-scope",
      "@radix-ui/react-popper",
      "@radix-ui/react-portal",
      "@radix-ui/react-roving-focus",
      "@radix-ui/react-presence",
      "@radix-ui/react-menu",
    ],
  },
};
