import { useEffect, useState, useMemo } from "react";
import { useNavigate } from "@tanstack/react-router";
import {
  Home,
  DoorOpen,
  Boxes,
  Calculator,
  Store,
  Gift,
  Bot,
  Mail,
  CreditCard,
  ShoppingBag,
  Sparkles,
  Video,
  Calendar,
  Share2,
  ShieldAlert,
  ClipboardList,
  Target,
  CircleAlert,
  BarChart3,
  Users,
  Settings,
  ShieldCheck,
  Moon,
  Sun,
  LogOut,
  FolderOpen,
  FlaskConical,
} from "lucide-react";
import {
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandSeparator,
} from "@/components/ui/command";
import { useAuth } from "@/hooks/use-auth";
import { useTheme } from "@/components/theme-provider";

interface ToolItem {
  id: string;
  name: string;
  description: string;
  group: string;
  to?: string;
  href?: string;
  icon: any;
  adminOnly?: boolean;
  marketingOnly?: boolean;
}

export function CommandPalette({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const navigate = useNavigate();
  const { isAdmin, roles, signOut } = useAuth();
  const { toggleTheme } = useTheme();

  const isMarketing = isAdmin || roles.includes("marketing_coordinator");
  const isVideoTeam =
    isAdmin ||
    roles.includes("marketing_coordinator") ||
    roles.includes("video_editor") ||
    roles.includes("videographer");

  const tools: ToolItem[] = useMemo(
    () => [
      // Market a Listing
      {
        id: "listings",
        name: "Active Listings & Graphics",
        description: "Under contract, pending, just listed packs & photos",
        group: "Market a Listing",
        to: "/listings",
        icon: Home,
      },
      {
        id: "open-houses",
        name: "Open Houses",
        description: "Schedule, live QR sign-in, attendee export & checklists",
        group: "Market a Listing",
        to: "/open-houses",
        icon: DoorOpen,
      },
      // Work With Clients
      {
        id: "seller-net",
        name: "Seller Net Proceeds Calculator",
        description: "Calculate & save estimated net proceeds for sellers",
        group: "Work With Clients",
        to: "/seller-net-proceeds",
        icon: Calculator,
      },
      {
        id: "vendors",
        name: "Trusted Vendor Guide",
        description: "Search 120+ local vetted home service contractors",
        group: "Work With Clients",
        to: "/vendors",
        icon: Store,
      },
      {
        id: "closing-gift",
        name: "Closing Gift Request",
        description: "Order client closing gifts & apparel",
        group: "Work With Clients",
        to: "/closing-gift",
        icon: Gift,
      },
      {
        id: "admin-net-sheets",
        name: "Agent Net Sheets",
        description: "View all seller net proceeds sheets generated by agents",
        group: "Operations",
        to: "/admin-net-sheets",
        icon: Calculator,
        adminOnly: true,
      },
      {
        id: "fub-assistant",
        name: "FUB AI Assistant",
        description: "Draft communication scripts and FUB message templates",
        group: "Work With Clients",
        to: "/admin/assistant",
        icon: Bot,
        adminOnly: true,
      },

      // My Brand
      {
        id: "signatures",
        name: "Email Signatures",
        description: "Branded Gmail signature generator & roster sync",
        group: "My Brand",
        to: "/signatures",
        icon: Mail,
      },
      {
        id: "toolbox",
        name: "Brand Assets & Toolbox",
        description: "Logos, headshots, NFC business cards & Canva templates",
        group: "My Brand",
        to: "/toolbox",
        icon: CreditCard,
      },

      // Perks & Events
      {
        id: "swag",
        name: "Swag Store & Credits",
        description: "Check swag credit balance and shop MSREG team store",
        group: "Perks & Events",
        to: "/admin/swag-credits",
        icon: ShoppingBag,
      },
      {
        id: "special-events",
        name: "Special Events",
        description: "RSVP for team summits, masterminds & events",
        group: "Perks & Events",
        to: "/special-events",
        icon: Sparkles,
      },

      // Team Workspace (Role-Gated)
      {
        id: "videos",
        name: "Video Pipeline",
        description: "Intake, editing & review kanban for video projects",
        group: "Team Workspace",
        to: "/videos",
        icon: Video,
        marketingOnly: true,
      },
      {
        id: "calendar",
        name: "Content Calendar",
        description: "Social media schedule, campaign planning & publishing",
        group: "Team Workspace",
        to: "/calendar",
        icon: Calendar,
        marketingOnly: true,
      },
      {
        id: "meta-social",
        name: "Social Publishing & Analytics",
        description: "Meta FB/IG direct publish, post performance & metrics",
        group: "Team Workspace",
        to: "/meta-social",
        icon: Share2,
        marketingOnly: true,
      },
      {
        id: "agent-audit",
        name: "Agent Audit System",
        description: "FUB compliance, activity grading & rubric review",
        group: "Team Workspace",
        to: "/admin/audit",
        icon: ShieldAlert,
        adminOnly: true,
      },

      // Operations
      {
        id: "tasks",
        name: "Projects & Tasks",
        description: "Internal team projects and operational tasks",
        group: "Operations",
        to: "/tasks",
        icon: ClipboardList,
      },
      {
        id: "inventory",
        name: "Closing Gifts & Inventory",
        description: "Track shirt inventory and fulfill agent gift requests",
        group: "Operations",
        to: "/inventory",
        icon: Boxes,
      },
      {
        id: "requests",
        name: "Marketing Requests Inbox",
        description: "Review incoming agent requests and custom graphic orders",
        group: "Operations",
        to: "/requests",
        icon: FolderOpen,
      },
      {
        id: "duty-calendar",
        name: "Duty Calendar",
        description: "Office phone duty shifts and coverage calendar",
        group: "Operations",
        to: "/duty-calendar",
        icon: Calendar,
      },
      {
        id: "eos-rocks",
        name: "EOS Rocks",
        description: "Quarterly company and individual priority rocks",
        group: "Operations",
        to: "/eos/rocks",
        icon: Target,
      },
      {
        id: "eos-issues",
        name: "EOS Issues List",
        description: "IDS issues tracking and resolution",
        group: "Operations",
        to: "/eos/issues",
        icon: CircleAlert,
      },
      {
        id: "eos-scorecard",
        name: "EOS Scorecard",
        description: "Weekly measurable scorecard metrics",
        group: "Operations",
        to: "/eos/scorecard",
        icon: BarChart3,
      },

      // Lab
      {
        id: "experiments",
        name: "Experiments & Lab",
        description: "Duty Calendar, Agent Audit System, Social & Meta, TV Dashboard",
        group: "Lab",
        to: "/experiments",
        icon: FlaskConical,
      },

      // Admin
      {
        id: "users",
        name: "User & Role Management",
        description: "Manage team member accounts and system permissions",
        group: "Admin",
        to: "/users",
        icon: Users,
        adminOnly: true,
      },
      {
        id: "audit-log",
        name: "Audit Trail Log",
        description: "System changes, security events and access logs",
        group: "Admin",
        to: "/audit-log",
        icon: ShieldCheck,
        adminOnly: true,
      },
    ],
    [],
  );

  const filteredTools = useMemo(() => {
    return tools.filter((t) => {
      if (t.adminOnly && !isAdmin) return false;
      if (t.marketingOnly && !isMarketing && !isVideoTeam) return false;
      return true;
    });
  }, [tools, isAdmin, isMarketing, isVideoTeam]);

  const groups = useMemo(() => {
    const list: Record<string, ToolItem[]> = {};
    filteredTools.forEach((t) => {
      if (!list[t.group]) list[t.group] = [];
      list[t.group].push(t);
    });
    return list;
  }, [filteredTools]);

  const handleSelect = (tool: ToolItem) => {
    onOpenChange(false);
    if (tool.to) {
      navigate({ to: tool.to as any });
    } else if (tool.href) {
      window.open(tool.href, "_blank");
    }
  };

  return (
    <CommandDialog open={open} onOpenChange={onOpenChange}>
      <CommandInput placeholder="Type a tool name or search actions..." />
      <CommandList className="max-h-[380px] overflow-y-auto">
        <CommandEmpty>No matching tools found.</CommandEmpty>

        {Object.entries(groups).map(([groupName, items], index) => (
          <CommandGroup key={groupName} heading={groupName}>
            {items.map((tool) => (
              <CommandItem
                key={tool.id}
                onSelect={() => handleSelect(tool)}
                className="flex items-center gap-3 px-3 py-2 cursor-pointer hover:bg-surface-2 rounded-md transition-colors"
              >
                <div className="h-7 w-7 rounded-md bg-surface-2 flex items-center justify-center shrink-0 text-accent">
                  <tool.icon className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="text-[13px] font-medium text-text-primary truncate">
                    {tool.name}
                  </div>
                  <div className="text-[11px] text-text-muted truncate">
                    {tool.description}
                  </div>
                </div>
              </CommandItem>
            ))}
            {index < Object.keys(groups).length - 1 && <CommandSeparator />}
          </CommandGroup>
        ))}

        <CommandSeparator />
        <CommandGroup heading="Quick Preferences">
          <CommandItem
            onSelect={() => {
              toggleTheme();
              onOpenChange(false);
            }}
            className="flex items-center gap-3 px-3 py-2 cursor-pointer hover:bg-surface-2 rounded-md"
          >
            <div className="h-7 w-7 rounded-md bg-surface-2 flex items-center justify-center shrink-0 text-text-secondary">
              <Sun className="h-4 w-4" />
            </div>
            <span className="text-[13px] text-text-primary">Toggle Dark / Light Theme</span>
          </CommandItem>
          <CommandItem
            onSelect={() => {
              onOpenChange(false);
              signOut();
            }}
            className="flex items-center gap-3 px-3 py-2 cursor-pointer hover:bg-surface-2 rounded-md"
          >
            <div className="h-7 w-7 rounded-md bg-surface-2 flex items-center justify-center shrink-0 text-status-danger">
              <LogOut className="h-4 w-4" />
            </div>
            <span className="text-[13px] text-text-primary">Sign Out</span>
          </CommandItem>
        </CommandGroup>
      </CommandList>
    </CommandDialog>
  );
}
