/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ClosingGiftRouteImport } from './routes/closing-gift'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentToolboxRouteImport } from './routes/agent-toolbox'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSignaturesRouteImport } from './routes/_authenticated/signatures'
import { Route as AuthenticatedToolboxRouteImport } from './routes/_authenticated/toolbox'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProcessesRouteImport } from './routes/_authenticated/processes'
import { Route as AuthenticatedMyAvailabilityRouteImport } from './routes/_authenticated/my-availability'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedDutyCalendarRouteImport } from './routes/_authenticated/duty-calendar'
import { Route as AuthenticatedDutyAgentsRouteImport } from './routes/_authenticated/duty-agents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedExperimentsIndexRouteImport } from './routes/_authenticated/experiments.index'
import { Route as AuthenticatedExperimentsVirtualStagingRouteImport } from './routes/_authenticated/experiments.virtual-staging'
import { Route as AuthenticatedExperimentsTvDashboardRouteImport } from './routes/_authenticated/experiments.tv-dashboard'
import { Route as AuthenticatedExperimentsLiveStatsRouteImport } from './routes/_authenticated/experiments.live-stats'
import { Route as AuthenticatedEosScorecardRouteImport } from './routes/_authenticated/eos.scorecard'
import { Route as AuthenticatedEosRocksRouteImport } from './routes/_authenticated/eos.rocks'
import { Route as AuthenticatedEosL10RouteImport } from './routes/_authenticated/eos.l10'
import { Route as AuthenticatedEosIssuesRouteImport } from './routes/_authenticated/eos.issues'
import { Route as AuthenticatedEosL10IndexRouteImport } from './routes/_authenticated/eos.l10.index'
import { Route as ApiPublicWebhooksInstantdecoRouteImport } from './routes/api/public/webhooks/instantdeco'
import { Route as ApiPublicHooksScorecardRemindersRouteImport } from './routes/api/public/hooks/scorecard-reminders'
import { Route as AuthenticatedEosL10IdRouteImport } from './routes/_authenticated/eos.l10.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosingGiftRoute = ClosingGiftRouteImport.update({
  id: '/closing-gift',
  path: '/closing-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentToolboxRoute = AgentToolboxRouteImport.update({
  id: '/agent-toolbox',
  path: '/agent-toolbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignaturesRoute = AuthenticatedSignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolboxRoute = AuthenticatedToolboxRouteImport.update({
  id: '/toolbox',
  path: '/toolbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessesRoute = AuthenticatedProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAvailabilityRoute =
  AuthenticatedMyAvailabilityRouteImport.update({
    id: '/my-availability',
    path: '/my-availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDutyCalendarRoute =
  AuthenticatedDutyCalendarRouteImport.update({
    id: '/duty-calendar',
    path: '/duty-calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDutyAgentsRoute = AuthenticatedDutyAgentsRouteImport.update({
  id: '/duty-agents',
  path: '/duty-agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsIndexRoute =
  AuthenticatedExperimentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedExperimentsVirtualStagingRoute =
  AuthenticatedExperimentsVirtualStagingRouteImport.update({
    id: '/virtual-staging',
    path: '/virtual-staging',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedExperimentsTvDashboardRoute =
  AuthenticatedExperimentsTvDashboardRouteImport.update({
    id: '/tv-dashboard',
    path: '/tv-dashboard',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedExperimentsLiveStatsRoute =
  AuthenticatedExperimentsLiveStatsRouteImport.update({
    id: '/live-stats',
    path: '/live-stats',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedEosScorecardRoute =
  AuthenticatedEosScorecardRouteImport.update({
    id: '/eos/scorecard',
    path: '/eos/scorecard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEosRocksRoute = AuthenticatedEosRocksRouteImport.update({
  id: '/eos/rocks',
  path: '/eos/rocks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEosL10Route = AuthenticatedEosL10RouteImport.update({
  id: '/eos/l10',
  path: '/eos/l10',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEosIssuesRoute = AuthenticatedEosIssuesRouteImport.update({
  id: '/eos/issues',
  path: '/eos/issues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEosL10IndexRoute =
  AuthenticatedEosL10IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEosL10Route,
  } as any)
const ApiPublicWebhooksInstantdecoRoute =
  ApiPublicWebhooksInstantdecoRouteImport.update({
    id: '/api/public/webhooks/instantdeco',
    path: '/api/public/webhooks/instantdeco',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScorecardRemindersRoute =
  ApiPublicHooksScorecardRemindersRouteImport.update({
    id: '/api/public/hooks/scorecard-reminders',
    path: '/api/public/hooks/scorecard-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEosL10IdRoute = AuthenticatedEosL10IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEosL10Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-toolbox': typeof AgentToolboxRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/closing-gift': typeof ClosingGiftRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duty-agents': typeof AuthenticatedDutyAgentsRoute
  '/duty-calendar': typeof AuthenticatedDutyCalendarRoute
  '/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-availability': typeof AuthenticatedMyAvailabilityRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/toolbox': typeof AuthenticatedToolboxRoute
  '/users': typeof AuthenticatedUsersRoute
  '/signatures': typeof AuthenticatedSignaturesRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/agents/': typeof AgentsIndexRoute
  '/eos/issues': typeof AuthenticatedEosIssuesRoute
  '/eos/l10': typeof AuthenticatedEosL10RouteWithChildren
  '/eos/rocks': typeof AuthenticatedEosRocksRoute
  '/eos/scorecard': typeof AuthenticatedEosScorecardRoute
  '/experiments/live-stats': typeof AuthenticatedExperimentsLiveStatsRoute
  '/experiments/tv-dashboard': typeof AuthenticatedExperimentsTvDashboardRoute
  '/experiments/virtual-staging': typeof AuthenticatedExperimentsVirtualStagingRoute
  '/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/eos/l10/$id': typeof AuthenticatedEosL10IdRoute
  '/api/public/hooks/scorecard-reminders': typeof ApiPublicHooksScorecardRemindersRoute
  '/api/public/webhooks/instantdeco': typeof ApiPublicWebhooksInstantdecoRoute
  '/eos/l10/': typeof AuthenticatedEosL10IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-toolbox': typeof AgentToolboxRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/closing-gift': typeof ClosingGiftRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duty-agents': typeof AuthenticatedDutyAgentsRoute
  '/duty-calendar': typeof AuthenticatedDutyCalendarRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-availability': typeof AuthenticatedMyAvailabilityRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/toolbox': typeof AuthenticatedToolboxRoute
  '/users': typeof AuthenticatedUsersRoute
  '/signatures': typeof AuthenticatedSignaturesRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/agents': typeof AgentsIndexRoute
  '/eos/issues': typeof AuthenticatedEosIssuesRoute
  '/eos/rocks': typeof AuthenticatedEosRocksRoute
  '/eos/scorecard': typeof AuthenticatedEosScorecardRoute
  '/experiments/live-stats': typeof AuthenticatedExperimentsLiveStatsRoute
  '/experiments/tv-dashboard': typeof AuthenticatedExperimentsTvDashboardRoute
  '/experiments/virtual-staging': typeof AuthenticatedExperimentsVirtualStagingRoute
  '/experiments': typeof AuthenticatedExperimentsIndexRoute
  '/eos/l10/$id': typeof AuthenticatedEosL10IdRoute
  '/api/public/hooks/scorecard-reminders': typeof ApiPublicHooksScorecardRemindersRoute
  '/api/public/webhooks/instantdeco': typeof ApiPublicWebhooksInstantdecoRoute
  '/eos/l10': typeof AuthenticatedEosL10IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agent-toolbox': typeof AgentToolboxRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/closing-gift': typeof ClosingGiftRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duty-agents': typeof AuthenticatedDutyAgentsRoute
  '/_authenticated/duty-calendar': typeof AuthenticatedDutyCalendarRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/my-availability': typeof AuthenticatedMyAvailabilityRoute
  '/_authenticated/processes': typeof AuthenticatedProcessesRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/toolbox': typeof AuthenticatedToolboxRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/signatures': typeof AuthenticatedSignaturesRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/agents/': typeof AgentsIndexRoute
  '/_authenticated/eos/issues': typeof AuthenticatedEosIssuesRoute
  '/_authenticated/eos/l10': typeof AuthenticatedEosL10RouteWithChildren
  '/_authenticated/eos/rocks': typeof AuthenticatedEosRocksRoute
  '/_authenticated/eos/scorecard': typeof AuthenticatedEosScorecardRoute
  '/_authenticated/experiments/live-stats': typeof AuthenticatedExperimentsLiveStatsRoute
  '/_authenticated/experiments/tv-dashboard': typeof AuthenticatedExperimentsTvDashboardRoute
  '/_authenticated/experiments/virtual-staging': typeof AuthenticatedExperimentsVirtualStagingRoute
  '/_authenticated/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/_authenticated/eos/l10/$id': typeof AuthenticatedEosL10IdRoute
  '/api/public/hooks/scorecard-reminders': typeof ApiPublicHooksScorecardRemindersRoute
  '/api/public/webhooks/instantdeco': typeof ApiPublicWebhooksInstantdecoRoute
  '/_authenticated/eos/l10/': typeof AuthenticatedEosL10IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-toolbox'
    | '/agents'
    | '/auth'
    | '/availability'
    | '/closing-gift'
    | '/request'
    | '/reset-password'
    | '/archive'
    | '/audit-log'
    | '/calendar'
    | '/dashboard'
    | '/duty-agents'
    | '/duty-calendar'
    | '/experiments'
    | '/inventory'
    | '/my-availability'
    | '/processes'
    | '/requests'
    | '/tasks'
    | '/toolbox'
    | '/users'
    | '/signatures'
    | '/videos'
    | '/agents/'
    | '/eos/issues'
    | '/eos/l10'
    | '/eos/rocks'
    | '/eos/scorecard'
    | '/experiments/live-stats'
    | '/experiments/tv-dashboard'
    | '/experiments/virtual-staging'
    | '/experiments/'
    | '/eos/l10/$id'
    | '/api/public/hooks/scorecard-reminders'
    | '/api/public/webhooks/instantdeco'
    | '/eos/l10/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-toolbox'
    | '/auth'
    | '/availability'
    | '/closing-gift'
    | '/request'
    | '/reset-password'
    | '/archive'
    | '/audit-log'
    | '/calendar'
    | '/dashboard'
    | '/duty-agents'
    | '/duty-calendar'
    | '/inventory'
    | '/my-availability'
    | '/processes'
    | '/requests'
    | '/tasks'
    | '/toolbox'
    | '/users'
    | '/signatures'
    | '/videos'
    | '/agents'
    | '/eos/issues'
    | '/eos/rocks'
    | '/eos/scorecard'
    | '/experiments/live-stats'
    | '/experiments/tv-dashboard'
    | '/experiments/virtual-staging'
    | '/experiments'
    | '/eos/l10/$id'
    | '/api/public/hooks/scorecard-reminders'
    | '/api/public/webhooks/instantdeco'
    | '/eos/l10'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agent-toolbox'
    | '/agents'
    | '/auth'
    | '/availability'
    | '/closing-gift'
    | '/request'
    | '/reset-password'
    | '/_authenticated/archive'
    | '/_authenticated/audit-log'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/duty-agents'
    | '/_authenticated/duty-calendar'
    | '/_authenticated/experiments'
    | '/_authenticated/inventory'
    | '/_authenticated/my-availability'
    | '/_authenticated/processes'
    | '/_authenticated/requests'
    | '/_authenticated/tasks'
    | '/_authenticated/toolbox'
    | '/_authenticated/users'
    | '/_authenticated/videos'
    | '/agents/'
    | '/_authenticated/eos/issues'
    | '/_authenticated/eos/l10'
    | '/_authenticated/eos/rocks'
    | '/_authenticated/eos/scorecard'
    | '/_authenticated/experiments/live-stats'
    | '/_authenticated/experiments/tv-dashboard'
    | '/_authenticated/experiments/virtual-staging'
    | '/_authenticated/experiments/'
    | '/_authenticated/eos/l10/$id'
    | '/api/public/hooks/scorecard-reminders'
    | '/api/public/webhooks/instantdeco'
    | '/_authenticated/eos/l10/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentToolboxRoute: typeof AgentToolboxRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvailabilityRoute: typeof AvailabilityRoute
  ClosingGiftRoute: typeof ClosingGiftRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksScorecardRemindersRoute: typeof ApiPublicHooksScorecardRemindersRoute
  ApiPublicWebhooksInstantdecoRoute: typeof ApiPublicWebhooksInstantdecoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closing-gift': {
      id: '/closing-gift'
      path: '/closing-gift'
      fullPath: '/closing-gift'
      preLoaderRoute: typeof ClosingGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-toolbox': {
      id: '/agent-toolbox'
      path: '/agent-toolbox'
      fullPath: '/agent-toolbox'
      preLoaderRoute: typeof AgentToolboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolbox': {
      id: '/_authenticated/toolbox'
      path: '/toolbox'
      fullPath: '/toolbox'
      preLoaderRoute: typeof AuthenticatedToolboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processes': {
      id: '/_authenticated/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthenticatedProcessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-availability': {
      id: '/_authenticated/my-availability'
      path: '/my-availability'
      fullPath: '/my-availability'
      preLoaderRoute: typeof AuthenticatedMyAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duty-calendar': {
      id: '/_authenticated/duty-calendar'
      path: '/duty-calendar'
      fullPath: '/duty-calendar'
      preLoaderRoute: typeof AuthenticatedDutyCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duty-agents': {
      id: '/_authenticated/duty-agents'
      path: '/duty-agents'
      fullPath: '/duty-agents'
      preLoaderRoute: typeof AuthenticatedDutyAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments/': {
      id: '/_authenticated/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof AuthenticatedExperimentsIndexRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/experiments/virtual-staging': {
      id: '/_authenticated/experiments/virtual-staging'
      path: '/virtual-staging'
      fullPath: '/experiments/virtual-staging'
      preLoaderRoute: typeof AuthenticatedExperimentsVirtualStagingRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/experiments/tv-dashboard': {
      id: '/_authenticated/experiments/tv-dashboard'
      path: '/tv-dashboard'
      fullPath: '/experiments/tv-dashboard'
      preLoaderRoute: typeof AuthenticatedExperimentsTvDashboardRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/experiments/live-stats': {
      id: '/_authenticated/experiments/live-stats'
      path: '/live-stats'
      fullPath: '/experiments/live-stats'
      preLoaderRoute: typeof AuthenticatedExperimentsLiveStatsRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/eos/scorecard': {
      id: '/_authenticated/eos/scorecard'
      path: '/eos/scorecard'
      fullPath: '/eos/scorecard'
      preLoaderRoute: typeof AuthenticatedEosScorecardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eos/rocks': {
      id: '/_authenticated/eos/rocks'
      path: '/eos/rocks'
      fullPath: '/eos/rocks'
      preLoaderRoute: typeof AuthenticatedEosRocksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eos/l10': {
      id: '/_authenticated/eos/l10'
      path: '/eos/l10'
      fullPath: '/eos/l10'
      preLoaderRoute: typeof AuthenticatedEosL10RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eos/issues': {
      id: '/_authenticated/eos/issues'
      path: '/eos/issues'
      fullPath: '/eos/issues'
      preLoaderRoute: typeof AuthenticatedEosIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eos/l10/': {
      id: '/_authenticated/eos/l10/'
      path: '/'
      fullPath: '/eos/l10/'
      preLoaderRoute: typeof AuthenticatedEosL10IndexRouteImport
      parentRoute: typeof AuthenticatedEosL10Route
    }
    '/api/public/webhooks/instantdeco': {
      id: '/api/public/webhooks/instantdeco'
      path: '/api/public/webhooks/instantdeco'
      fullPath: '/api/public/webhooks/instantdeco'
      preLoaderRoute: typeof ApiPublicWebhooksInstantdecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scorecard-reminders': {
      id: '/api/public/hooks/scorecard-reminders'
      path: '/api/public/hooks/scorecard-reminders'
      fullPath: '/api/public/hooks/scorecard-reminders'
      preLoaderRoute: typeof ApiPublicHooksScorecardRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eos/l10/$id': {
      id: '/_authenticated/eos/l10/$id'
      path: '/$id'
      fullPath: '/eos/l10/$id'
      preLoaderRoute: typeof AuthenticatedEosL10IdRouteImport
      parentRoute: typeof AuthenticatedEosL10Route
    }
  }
}

interface AuthenticatedExperimentsRouteChildren {
  AuthenticatedExperimentsLiveStatsRoute: typeof AuthenticatedExperimentsLiveStatsRoute
  AuthenticatedExperimentsTvDashboardRoute: typeof AuthenticatedExperimentsTvDashboardRoute
  AuthenticatedExperimentsVirtualStagingRoute: typeof AuthenticatedExperimentsVirtualStagingRoute
  AuthenticatedExperimentsIndexRoute: typeof AuthenticatedExperimentsIndexRoute
}

const AuthenticatedExperimentsRouteChildren: AuthenticatedExperimentsRouteChildren =
  {
    AuthenticatedExperimentsLiveStatsRoute:
      AuthenticatedExperimentsLiveStatsRoute,
    AuthenticatedExperimentsTvDashboardRoute:
      AuthenticatedExperimentsTvDashboardRoute,
    AuthenticatedExperimentsVirtualStagingRoute:
      AuthenticatedExperimentsVirtualStagingRoute,
    AuthenticatedExperimentsIndexRoute: AuthenticatedExperimentsIndexRoute,
  }

const AuthenticatedExperimentsRouteWithChildren =
  AuthenticatedExperimentsRoute._addFileChildren(
    AuthenticatedExperimentsRouteChildren,
  )

interface AuthenticatedEosL10RouteChildren {
  AuthenticatedEosL10IdRoute: typeof AuthenticatedEosL10IdRoute
  AuthenticatedEosL10IndexRoute: typeof AuthenticatedEosL10IndexRoute
}

const AuthenticatedEosL10RouteChildren: AuthenticatedEosL10RouteChildren = {
  AuthenticatedEosL10IdRoute: AuthenticatedEosL10IdRoute,
  AuthenticatedEosL10IndexRoute: AuthenticatedEosL10IndexRoute,
}

const AuthenticatedEosL10RouteWithChildren =
  AuthenticatedEosL10Route._addFileChildren(AuthenticatedEosL10RouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDutyAgentsRoute: typeof AuthenticatedDutyAgentsRoute
  AuthenticatedDutyCalendarRoute: typeof AuthenticatedDutyCalendarRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMyAvailabilityRoute: typeof AuthenticatedMyAvailabilityRoute
  AuthenticatedProcessesRoute: typeof AuthenticatedProcessesRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedToolboxRoute: typeof AuthenticatedToolboxRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedSignaturesRoute: typeof AuthenticatedSignaturesRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedEosIssuesRoute: typeof AuthenticatedEosIssuesRoute
  AuthenticatedEosL10Route: typeof AuthenticatedEosL10RouteWithChildren
  AuthenticatedEosRocksRoute: typeof AuthenticatedEosRocksRoute
  AuthenticatedEosScorecardRoute: typeof AuthenticatedEosScorecardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDutyAgentsRoute: AuthenticatedDutyAgentsRoute,
  AuthenticatedDutyCalendarRoute: AuthenticatedDutyCalendarRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMyAvailabilityRoute: AuthenticatedMyAvailabilityRoute,
  AuthenticatedProcessesRoute: AuthenticatedProcessesRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedToolboxRoute: AuthenticatedToolboxRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedSignaturesRoute: AuthenticatedSignaturesRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedEosIssuesRoute: AuthenticatedEosIssuesRoute,
  AuthenticatedEosL10Route: AuthenticatedEosL10RouteWithChildren,
  AuthenticatedEosRocksRoute: AuthenticatedEosRocksRoute,
  AuthenticatedEosScorecardRoute: AuthenticatedEosScorecardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgentsRouteChildren {
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentToolboxRoute: AgentToolboxRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRoute,
  AvailabilityRoute: AvailabilityRoute,
  ClosingGiftRoute: ClosingGiftRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksScorecardRemindersRoute: ApiPublicHooksScorecardRemindersRoute,
  ApiPublicWebhooksInstantdecoRoute: ApiPublicWebhooksInstantdecoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
